/**
 * API Types Template
 *
 * Generates TypeScript type definition files for APIs.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { APIAnalysis } from '../backend-team.types';
import { toResourceName, toPascalCase } from '../utils/naming.utils';

/**
 * Generate API types file
 */
export function generateAPITypes(
  task: TaskDocument,
  _analysis: APIAnalysis
): GeneratedFile {
  const resourceName = toResourceName(task.title);
  const typeName = toPascalCase(resourceName);

  const content = `/**
 * Types for ${task.title} API
 *
 * @generated by Backend Team
 */

export interface ${typeName} {
  id: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Create${typeName}Request {
  // Request body for creating ${resourceName}
}

export interface Update${typeName}Request {
  // Request body for updating ${resourceName}
}

export interface ${typeName}Response {
  data: ${typeName};
  message?: string;
}

export interface ${typeName}ListResponse {
  data: ${typeName}[];
  total: number;
  page: number;
  limit: number;
}

export interface ${typeName}Query {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  search?: string;
}
`;

  return {
    path: `src/types/${resourceName}.types.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}
