/**
 * Controller Template
 *
 * Generates Express controller files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { APIAnalysis, BackendTeamConfig } from '../backend-team.types';
import { toControllerName, toResourceName, toPascalCase } from '../utils/naming.utils';

/**
 * Generate GET method template
 */
export function generateGetMethod(resourceName: string): string {
  return `
  async getAll(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { page, limit, ...query } = req.query;
      const result = await this.${resourceName}Service.findAll({
        page: Number(page) || 1,
        limit: Number(limit) || 20,
      });
      res.json(result);
    } catch (error) {
      next(error);
    }
  }

  async getById(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;
      const result = await this.${resourceName}Service.findById(id);
      res.json({ data: result });
    } catch (error) {
      next(error);
    }
  }`;
}

/**
 * Generate POST method template
 */
export function generatePostMethod(resourceName: string): string {
  return `
  async create(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const data = req.body;
      const result = await this.${resourceName}Service.create(data);
      res.status(201).json({ data: result });
    } catch (error) {
      next(error);
    }
  }`;
}

/**
 * Generate PUT method template
 */
export function generatePutMethod(resourceName: string): string {
  return `
  async update(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;
      const data = req.body;
      const result = await this.${resourceName}Service.update(id, data);
      res.json({ data: result });
    } catch (error) {
      next(error);
    }
  }`;
}

/**
 * Generate DELETE method template
 */
export function generateDeleteMethod(resourceName: string): string {
  return `
  async delete(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;
      await this.${resourceName}Service.delete(id);
      res.status(204).send();
    } catch (error) {
      next(error);
    }
  }`;
}

/**
 * Generate controller file
 */
export function generateController(
  task: TaskDocument,
  analysis: APIAnalysis,
  config: BackendTeamConfig
): GeneratedFile {
  const controllerName = toControllerName(task.title);
  const resourceName = toResourceName(task.title);

  const content = `/**
 * ${controllerName}
 *
 * ${task.description}
 *
 * @generated by Backend Team
 */

import { Request, Response, NextFunction } from 'express';
import { ${resourceName}Service } from '../services/${resourceName}.service';
${config.enableValidation ? `import { ${resourceName}Schema } from '../validation/${resourceName}.validation';` : ''}

export class ${controllerName} {
  private ${resourceName}Service: ${toPascalCase(resourceName)}Service;

  constructor() {
    this.${resourceName}Service = new ${toPascalCase(resourceName)}Service();
  }

  ${analysis.httpMethods.includes('GET') ? generateGetMethod(resourceName) : ''}

  ${analysis.httpMethods.includes('POST') ? generatePostMethod(resourceName) : ''}

  ${analysis.httpMethods.includes('PUT') ? generatePutMethod(resourceName) : ''}

  ${analysis.httpMethods.includes('DELETE') ? generateDeleteMethod(resourceName) : ''}
}

export const ${resourceName}Controller = new ${controllerName}();
`;

  return {
    path: `src/controllers/${resourceName}.controller.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}
