/**
 * Middleware Template
 *
 * Generates Express middleware files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { toMiddlewareName, toCamelCase, toKebabCase } from '../utils/naming.utils';

/**
 * Generate middleware file
 */
export function generateMiddlewareFile(task: TaskDocument): GeneratedFile {
  const middlewareName = toMiddlewareName(task.title);
  const functionName = toCamelCase(task.title.replace(/middleware/gi, ''));

  const content = `/**
 * ${task.title} Middleware
 *
 * ${task.description}
 *
 * @generated by Backend Team
 */

import { Request, Response, NextFunction } from 'express';

export interface ${middlewareName}Options {
  // Middleware configuration options
}

export function ${functionName}(options: ${middlewareName}Options = {}) {
  return (req: Request, res: Response, next: NextFunction): void => {
    try {
      // Middleware logic here

      next();
    } catch (error) {
      next(error);
    }
  };
}

export default ${functionName};
`;

  return {
    path: `src/middleware/${toKebabCase(task.title)}.middleware.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}
