/**
 * Migration Template
 *
 * Generates SQL migration files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { ModelAnalysis } from '../backend-team.types';
import { toSnakeCase } from '../utils/naming.utils';
import { toSQLType } from '../utils/type-mapping';

/**
 * Generate migration file for model
 */
export function generateMigrationFile(
  _task: TaskDocument,
  analysis: ModelAnalysis
): GeneratedFile {
  const timestamp = Date.now();
  const tableName = toSnakeCase(analysis.entityName);

  const columnDefs = analysis.fields.map((field) => {
    const sqlType = toSQLType(field.type);
    const nullable = field.required ? 'NOT NULL' : 'NULL';
    const unique = field.unique ? 'UNIQUE' : '';

    if (field.name === 'id') {
      return `    id UUID PRIMARY KEY DEFAULT gen_random_uuid()`;
    }

    return `    ${toSnakeCase(field.name)} ${sqlType} ${nullable} ${unique}`.trim();
  });

  const content = `-- Migration: Create ${tableName}
-- Generated by Backend Team

CREATE TABLE ${tableName} (
${columnDefs.join(',\n')},
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create updated_at trigger
CREATE TRIGGER ${tableName}_updated_at
    BEFORE UPDATE ON ${tableName}
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Create indexes
CREATE INDEX idx_${tableName}_created_at ON ${tableName}(created_at);
`;

  return {
    path: `prisma/migrations/${timestamp}_create_${tableName}/migration.sql`,
    content,
    language: 'sql',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}

/**
 * Generate generic migration file
 */
export function generateMigration(task: TaskDocument): GeneratedFile {
  const timestamp = Date.now();
  const migrationName = toSnakeCase(task.title);

  const content = `-- Migration: ${task.title}
-- ${task.description}
-- Generated by Backend Team

-- Up Migration
-- TODO: Add migration SQL here

-- Down Migration
-- TODO: Add rollback SQL here
`;

  return {
    path: `prisma/migrations/${timestamp}_${migrationName}/migration.sql`,
    content,
    language: 'sql',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}
