/**
 * OpenAPI Template
 *
 * Generates OpenAPI specification files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { APIAnalysis } from '../backend-team.types';
import { toResourceName, toPascalCase } from '../utils/naming.utils';

/**
 * Generate OpenAPI specification file
 */
export function generateOpenAPISpec(
  task: TaskDocument,
  analysis: APIAnalysis
): GeneratedFile {
  const resourceName = toResourceName(task.title);
  const typeName = toPascalCase(resourceName);

  const content = `/**
 * OpenAPI Specification for ${task.title}
 *
 * @generated by Backend Team
 */

export const ${resourceName}OpenAPI = {
  paths: {
    '/${resourceName}s': {
      ${analysis.httpMethods.includes('GET') ? `get: {
        summary: 'List all ${resourceName}s',
        tags: ['${typeName}'],
        ${analysis.requiresAuth ? `security: [{ bearerAuth: [] }],` : ''}
        parameters: [
          { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
          { name: 'limit', in: 'query', schema: { type: 'integer', default: 20 } },
        ],
        responses: {
          200: { description: 'List of ${resourceName}s' },
          401: { description: 'Unauthorized' },
        },
      },` : ''}
      ${analysis.httpMethods.includes('POST') ? `post: {
        summary: 'Create a ${resourceName}',
        tags: ['${typeName}'],
        ${analysis.requiresAuth ? `security: [{ bearerAuth: [] }],` : ''}
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Create${typeName}' },
            },
          },
        },
        responses: {
          201: { description: '${typeName} created' },
          400: { description: 'Invalid input' },
          401: { description: 'Unauthorized' },
        },
      },` : ''}
    },
    '/${resourceName}s/{id}': {
      ${analysis.httpMethods.includes('GET') ? `get: {
        summary: 'Get a ${resourceName} by ID',
        tags: ['${typeName}'],
        parameters: [
          { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
        ],
        responses: {
          200: { description: '${typeName} found' },
          404: { description: '${typeName} not found' },
        },
      },` : ''}
      ${analysis.httpMethods.includes('PUT') ? `put: {
        summary: 'Update a ${resourceName}',
        tags: ['${typeName}'],
        ${analysis.requiresAuth ? `security: [{ bearerAuth: [] }],` : ''}
        parameters: [
          { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
        ],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/Update${typeName}' },
            },
          },
        },
        responses: {
          200: { description: '${typeName} updated' },
          404: { description: '${typeName} not found' },
        },
      },` : ''}
      ${analysis.httpMethods.includes('DELETE') ? `delete: {
        summary: 'Delete a ${resourceName}',
        tags: ['${typeName}'],
        ${analysis.requiresAuth ? `security: [{ bearerAuth: [] }],` : ''}
        parameters: [
          { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
        ],
        responses: {
          204: { description: '${typeName} deleted' },
          404: { description: '${typeName} not found' },
        },
      },` : ''}
    },
  },
};
`;

  return {
    path: `src/docs/${resourceName}.openapi.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}
