/**
 * Repository Template
 *
 * Generates Prisma repository files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { ModelAnalysis } from '../backend-team.types';

/**
 * Generate repository file
 */
export function generateRepository(
  _task: TaskDocument,
  analysis: ModelAnalysis
): GeneratedFile {
  const entityName = analysis.entityName;
  const varName = entityName.charAt(0).toLowerCase() + entityName.slice(1);

  const content = `/**
 * ${entityName} Repository
 *
 * @generated by Backend Team
 */

import { PrismaClient, ${entityName} } from '@prisma/client';

const prisma = new PrismaClient();

export interface ${entityName}Repository {
  findAll(options?: { skip?: number; take?: number }): Promise<${entityName}[]>;
  findById(id: string): Promise<${entityName} | null>;
  create(data: Omit<${entityName}, 'id' | 'createdAt' | 'updatedAt'>): Promise<${entityName}>;
  update(id: string, data: Partial<${entityName}>): Promise<${entityName}>;
  delete(id: string): Promise<void>;
  count(): Promise<number>;
}

export class Prisma${entityName}Repository implements ${entityName}Repository {
  async findAll(options?: { skip?: number; take?: number }): Promise<${entityName}[]> {
    return prisma.${varName}.findMany({
      skip: options?.skip,
      take: options?.take,
      orderBy: { createdAt: 'desc' },
    });
  }

  async findById(id: string): Promise<${entityName} | null> {
    return prisma.${varName}.findUnique({
      where: { id },
    });
  }

  async create(data: Omit<${entityName}, 'id' | 'createdAt' | 'updatedAt'>): Promise<${entityName}> {
    return prisma.${varName}.create({
      data,
    });
  }

  async update(id: string, data: Partial<${entityName}>): Promise<${entityName}> {
    return prisma.${varName}.update({
      where: { id },
      data,
    });
  }

  async delete(id: string): Promise<void> {
    await prisma.${varName}.delete({
      where: { id },
    });
  }

  async count(): Promise<number> {
    return prisma.${varName}.count();
  }
}

export const ${varName}Repository = new Prisma${entityName}Repository();
`;

  return {
    path: `src/repositories/${varName}.repository.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}
