/**
 * Routes Template
 *
 * Generates Express route files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { APIAnalysis, BackendTeamConfig } from '../backend-team.types';
import { toResourceName } from '../utils/naming.utils';

/**
 * Generate routes file
 */
export function generateRoutes(
  task: TaskDocument,
  analysis: APIAnalysis,
  config: BackendTeamConfig
): GeneratedFile {
  const resourceName = toResourceName(task.title);

  const content = `/**
 * ${task.title} Routes
 *
 * @generated by Backend Team
 */

import { Router } from 'express';
import { ${resourceName}Controller } from '../controllers/${resourceName}.controller';
${config.enableAuth ? `import { authenticate } from '../middleware/auth.middleware';` : ''}
${config.enableValidation ? `import { validate } from '../middleware/validation.middleware';` : ''}
${config.enableRateLimiting ? `import { rateLimiter } from '../middleware/rate-limiter.middleware';` : ''}

const router = Router();

${analysis.httpMethods.includes('GET') ? `
// GET /${resourceName}s - List all
router.get('/', ${config.enableRateLimiting ? 'rateLimiter, ' : ''}${analysis.requiresAuth ? 'authenticate, ' : ''}${resourceName}Controller.getAll.bind(${resourceName}Controller));

// GET /${resourceName}s/:id - Get one
router.get('/:id', ${analysis.requiresAuth ? 'authenticate, ' : ''}${resourceName}Controller.getById.bind(${resourceName}Controller));
` : ''}

${analysis.httpMethods.includes('POST') ? `
// POST /${resourceName}s - Create
router.post('/', ${analysis.requiresAuth ? 'authenticate, ' : ''}${config.enableValidation ? `validate(${resourceName}Schema.create), ` : ''}${resourceName}Controller.create.bind(${resourceName}Controller));
` : ''}

${analysis.httpMethods.includes('PUT') ? `
// PUT /${resourceName}s/:id - Update
router.put('/:id', ${analysis.requiresAuth ? 'authenticate, ' : ''}${config.enableValidation ? `validate(${resourceName}Schema.update), ` : ''}${resourceName}Controller.update.bind(${resourceName}Controller));
` : ''}

${analysis.httpMethods.includes('DELETE') ? `
// DELETE /${resourceName}s/:id - Delete
router.delete('/:id', ${analysis.requiresAuth ? 'authenticate, ' : ''}${resourceName}Controller.delete.bind(${resourceName}Controller));
` : ''}

export default router;
`;

  return {
    path: `src/routes/${resourceName}.routes.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}
