/**
 * Seed Template
 *
 * Generates database seed files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { ModelAnalysis } from '../backend-team.types';

/**
 * Generate seed file
 */
export function generateSeedFile(
  _task: TaskDocument,
  analysis: ModelAnalysis
): GeneratedFile {
  const entityName = analysis.entityName;
  const varName = entityName.charAt(0).toLowerCase() + entityName.slice(1);

  const content = `/**
 * Seed data for ${entityName}
 *
 * @generated by Backend Team
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seed${entityName}s(): Promise<void> {
  console.log('Seeding ${entityName}s...');

  const ${varName}s = [
    {
      // Add seed data here
    },
  ];

  for (const ${varName} of ${varName}s) {
    await prisma.${varName}.create({
      data: ${varName},
    });
  }

  console.log(\`Seeded \${${varName}s.length} ${entityName}s\`);
}

// Run if executed directly
if (require.main === module) {
  seed${entityName}s()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
}
`;

  return {
    path: `prisma/seeds/${varName}.seed.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}
