/**
 * Validation Template
 *
 * Generates Zod validation schema files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { APIAnalysis } from '../backend-team.types';
import { toResourceName, toPascalCase } from '../utils/naming.utils';

/**
 * Generate validation schema file
 */
export function generateValidation(
  task: TaskDocument,
  analysis: APIAnalysis
): GeneratedFile {
  const resourceName = toResourceName(task.title);
  const pascalName = toPascalCase(resourceName);

  const content = `/**
 * Validation schemas for ${task.title}
 *
 * @generated by Backend Team
 */

import { z } from 'zod';

export const ${resourceName}Schema = {
  create: z.object({
    ${analysis.validationRequirements.includes('email') ? 'email: z.string().email(),' : ''}
    ${analysis.validationRequirements.includes('password-strength') ? `password: z.string().min(8).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)/),` : ''}
    name: z.string().min(1).max(255),
  }),

  update: z.object({
    ${analysis.validationRequirements.includes('email') ? 'email: z.string().email().optional(),' : ''}
    name: z.string().min(1).max(255).optional(),
  }),

  query: z.object({
    page: z.coerce.number().int().positive().default(1),
    limit: z.coerce.number().int().positive().max(100).default(20),
    sortBy: z.string().optional(),
    sortOrder: z.enum(['asc', 'desc']).default('asc'),
    search: z.string().optional(),
  }),
};

export type Create${pascalName}Input = z.infer<typeof ${resourceName}Schema.create>;
export type Update${pascalName}Input = z.infer<typeof ${resourceName}Schema.update>;
export type ${pascalName}QueryInput = z.infer<typeof ${resourceName}Schema.query>;
`;

  return {
    path: `src/validation/${resourceName}.validation.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: false,
  };
}
