/**
 * Accessibility Templates
 *
 * Templates for generating accessibility-related code.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';

/**
 * Generate accessibility utilities file
 */
export function generateA11yUtilsFile(task: TaskDocument): string {
  return `/**
 * Accessibility Utilities
 *
 * ${task.description}
 *
 * @generated by Frontend Team
 */

/**
 * Visually hidden but accessible to screen readers
 */
export const visuallyHidden: React.CSSProperties = {
  position: 'absolute',
  width: '1px',
  height: '1px',
  padding: 0,
  margin: '-1px',
  overflow: 'hidden',
  clip: 'rect(0, 0, 0, 0)',
  whiteSpace: 'nowrap',
  border: 0,
};

/**
 * Create an accessible label
 */
export function createAriaLabel(text: string, context?: string): string {
  return context ? \`\${text}, \${context}\` : text;
}

/**
 * Announce to screen readers
 */
export function announce(message: string, priority: 'polite' | 'assertive' = 'polite'): void {
  const announcement = document.createElement('div');
  announcement.setAttribute('role', 'status');
  announcement.setAttribute('aria-live', priority);
  announcement.setAttribute('aria-atomic', 'true');
  Object.assign(announcement.style, visuallyHidden);
  announcement.textContent = message;

  document.body.appendChild(announcement);

  setTimeout(() => {
    document.body.removeChild(announcement);
  }, 1000);
}

/**
 * Trap focus within an element
 */
export function trapFocus(element: HTMLElement): () => void {
  const focusableElements = element.querySelectorAll<HTMLElement>(
    'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
  );

  const firstFocusable = focusableElements[0];
  const lastFocusable = focusableElements[focusableElements.length - 1];

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key !== 'Tab') return;

    if (e.shiftKey) {
      if (document.activeElement === firstFocusable) {
        lastFocusable.focus();
        e.preventDefault();
      }
    } else {
      if (document.activeElement === lastFocusable) {
        firstFocusable.focus();
        e.preventDefault();
      }
    }
  };

  element.addEventListener('keydown', handleKeyDown);
  firstFocusable?.focus();

  return () => {
    element.removeEventListener('keydown', handleKeyDown);
  };
}

/**
 * Check if element has sufficient color contrast
 */
export function hassufficientContrast(
  foreground: string,
  background: string,
  level: 'AA' | 'AAA' = 'AA'
): boolean {
  // Simplified contrast check
  // In production, use a proper color contrast library
  const threshold = level === 'AAA' ? 7 : 4.5;
  return true; // Placeholder - implement proper contrast calculation
}
`;
}

/**
 * Generate skip links component
 */
export function generateSkipLinksComponent(): string {
  return `/**
 * Skip Links Component
 *
 * Provides keyboard-accessible skip links for navigation.
 *
 * @generated by Frontend Team
 */

import React from 'react';
import './SkipLinks.css';

export interface SkipLink {
  /** Target element ID */
  targetId: string;
  /** Link text */
  text: string;
}

export interface SkipLinksProps {
  /** Skip links configuration */
  links?: SkipLink[];
}

const defaultLinks: SkipLink[] = [
  { targetId: 'main-content', text: 'Skip to main content' },
  { targetId: 'main-navigation', text: 'Skip to navigation' },
];

/**
 * Skip links for keyboard navigation
 */
export const SkipLinks: React.FC<SkipLinksProps> = ({ links = defaultLinks }) => {
  const handleClick = (e: React.MouseEvent<HTMLAnchorElement>, targetId: string) => {
    e.preventDefault();
    const target = document.getElementById(targetId);
    if (target) {
      target.focus();
      target.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <nav className="skip-links" aria-label="Skip links">
      {links.map((link) => (
        <a
          key={link.targetId}
          href={\`#\${link.targetId}\`}
          className="skip-links__link"
          onClick={(e) => handleClick(e, link.targetId)}
        >
          {link.text}
        </a>
      ))}
    </nav>
  );
};

export default SkipLinks;
`;
}

/**
 * Generate accessibility documentation
 */
export function generateA11yDocumentation(task: TaskDocument): string {
  return `# Accessibility Guidelines

## Description
${task.description}

## WCAG 2.1 Compliance

### Level A
- All images have alt text
- All form inputs have labels
- Color is not the only means of conveying information

### Level AA
- Color contrast ratio is at least 4.5:1 for normal text
- Focus states are visible
- Headings are properly structured

### Level AAA
- Color contrast ratio is at least 7:1
- Sign language interpretation for video

## Implementation

### Skip Links
Use the SkipLinks component to provide keyboard shortcuts.

### Focus Management
Use the trapFocus utility for modal dialogs.

### Screen Reader Announcements
Use the announce utility for dynamic updates.

## Testing

Run accessibility tests:
\`\`\`bash
npm run test:a11y
\`\`\`
`;
}
