/**
 * React Component Template
 *
 * Template for generating React components.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { ComponentAnalysis } from '../frontend-team.types';
import { toKebabCase } from '../utils';
import { generateA11yProps } from '../utils/a11y.utils';

/**
 * Generate React component code
 */
export function generateReactComponent(
  task: TaskDocument,
  componentName: string,
  analysis: ComponentAnalysis,
  cssApproach?: string
): string {
  const hasProps = analysis.hasChildren || analysis.requiresAPI;
  const hasState = analysis.requiresState;
  const hasEffect = analysis.requiresAPI;

  const imports = [
    `import React${hasState ? ', { useState }' : ''}${hasEffect ? ', { useEffect }' : ''} from 'react';`,
  ];

  if (cssApproach === 'styled-components') {
    imports.push(`import styled from 'styled-components';`);
  }

  const propsInterface = hasProps
    ? `
export interface ${componentName}Props {
  ${analysis.hasChildren ? 'children?: React.ReactNode;' : ''}
  ${analysis.requiresAPI ? 'data?: unknown;' : ''}
  className?: string;
}`
    : `
export interface ${componentName}Props {
  className?: string;
}`;

  const stateDeclaration = hasState
    ? `
  const [isActive, setIsActive] = useState(false);`
    : '';

  const effectDeclaration = hasEffect
    ? `
  useEffect(() => {
    // Load data on mount
  }, []);`
    : '';

  const a11yProps = analysis.a11yRequirements.length > 0
    ? generateA11yProps(analysis.a11yRequirements)
    : '';

  return `/**
 * ${componentName}
 *
 * ${task.description}
 *
 * @generated by Frontend Team
 */

${imports.join('\n')}
import './${componentName}.css';
${propsInterface}

/**
 * ${task.description}
 */
export const ${componentName}: React.FC<${componentName}Props> = ({
  ${analysis.hasChildren ? 'children,' : ''}
  className,
}) => {${stateDeclaration}${effectDeclaration}

  return (
    <div
      className={\`${toKebabCase(componentName)} \${className || ''}\`}
      ${a11yProps}
    >
      {/* Component content */}
      ${analysis.hasChildren ? '{children}' : `<span>${task.title}</span>`}
    </div>
  );
};

export default ${componentName};
`;
}

/**
 * Generate page component code
 */
export function generatePageComponent(
  task: TaskDocument,
  pageName: string
): string {
  return `/**
 * ${pageName} Page
 *
 * ${task.description}
 *
 * @generated by Frontend Team
 */

import React from 'react';
import './${pageName}.css';

export interface ${pageName}PageProps {
  /** Page parameters */
  params?: Record<string, string>;
}

/**
 * ${task.description}
 */
export const ${pageName}Page: React.FC<${pageName}PageProps> = ({ params }) => {
  return (
    <main className="${toKebabCase(pageName)}-page">
      <header className="${toKebabCase(pageName)}-page__header">
        <h1>${task.title}</h1>
      </header>

      <section className="${toKebabCase(pageName)}-page__content">
        {/* Page content */}
      </section>

      <footer className="${toKebabCase(pageName)}-page__footer">
        {/* Page footer */}
      </footer>
    </main>
  );
};

export default ${pageName}Page;
`;
}

/**
 * Generate layout component code
 */
export function generateLayoutComponent(
  _task: TaskDocument,
  layoutName: string
): string {
  return `/**
 * ${layoutName} Layout
 *
 * @generated by Frontend Team
 */

import React from 'react';

export interface ${layoutName}LayoutProps {
  children: React.ReactNode;
}

export const ${layoutName}Layout: React.FC<${layoutName}LayoutProps> = ({ children }) => {
  return (
    <div className="${toKebabCase(layoutName)}-layout">
      <nav className="${toKebabCase(layoutName)}-layout__nav">
        {/* Navigation */}
      </nav>

      <main className="${toKebabCase(layoutName)}-layout__main">
        {children}
      </main>

      <aside className="${toKebabCase(layoutName)}-layout__sidebar">
        {/* Sidebar */}
      </aside>
    </div>
  );
};

export default ${layoutName}Layout;
`;
}
