/**
 * Style Templates
 *
 * Templates for generating CSS and styling files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { ComponentAnalysis } from '../frontend-team.types';
import { toComponentName, toKebabCase } from '../utils';
import { generateBreakpointStyle } from '../utils/a11y.utils';

/**
 * Generate component style file
 */
export function generateComponentStyle(
  task: TaskDocument,
  analysis: ComponentAnalysis
): string {
  const componentName = toComponentName(task.title);
  const className = toKebabCase(componentName);

  const breakpointStyles = analysis.responsiveBreakpoints
    .map((bp) => generateBreakpointStyle(bp, className))
    .join('\n');

  return `/**
 * Styles for ${componentName}
 *
 * @generated by Frontend Team
 */

.${className} {
  /* Base styles */
  display: flex;
  flex-direction: column;
}

.${className}__content {
  /* Content area */
}

.${className}__header {
  /* Header area */
}

.${className}__footer {
  /* Footer area */
}

/* State variations */
.${className}--active {
  /* Active state */
}

.${className}--disabled {
  opacity: 0.5;
  pointer-events: none;
}

/* Responsive styles */
${breakpointStyles}
`;
}

/**
 * Generate main style file
 */
export function generateMainStyle(task: TaskDocument): string {
  return `/**
 * ${task.title}
 *
 * ${task.description}
 *
 * @generated by Frontend Team
 */

/* Reset and base styles */
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

/* Root variables */
:root {
  /* Colors */
  --color-primary: #3b82f6;
  --color-secondary: #6b7280;
  --color-success: #10b981;
  --color-warning: #f59e0b;
  --color-error: #ef4444;

  /* Typography */
  --font-family-base: system-ui, -apple-system, sans-serif;
  --font-size-base: 1rem;
  --line-height-base: 1.5;

  /* Spacing */
  --spacing-xs: 0.25rem;
  --spacing-sm: 0.5rem;
  --spacing-md: 1rem;
  --spacing-lg: 1.5rem;
  --spacing-xl: 2rem;

  /* Borders */
  --border-radius-sm: 0.25rem;
  --border-radius-md: 0.5rem;
  --border-radius-lg: 1rem;
}

/* Base body styles */
body {
  font-family: var(--font-family-base);
  font-size: var(--font-size-base);
  line-height: var(--line-height-base);
}

/* Focus styles for accessibility */
:focus-visible {
  outline: 2px solid var(--color-primary);
  outline-offset: 2px;
}
`;
}

/**
 * Generate theme file
 */
export function generateTheme(task: TaskDocument): string {
  return `/**
 * Theme Configuration
 *
 * ${task.description}
 *
 * @generated by Frontend Team
 */

export const lightTheme = {
  colors: {
    background: '#ffffff',
    surface: '#f9fafb',
    text: {
      primary: '#111827',
      secondary: '#6b7280',
      disabled: '#9ca3af',
    },
    border: '#e5e7eb',
    primary: '#3b82f6',
    secondary: '#6b7280',
    success: '#10b981',
    warning: '#f59e0b',
    error: '#ef4444',
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
  },
  typography: {
    fontFamily: 'system-ui, -apple-system, sans-serif',
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  borderRadius: {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '1rem',
    full: '9999px',
  },
};

export const darkTheme = {
  ...lightTheme,
  colors: {
    background: '#111827',
    surface: '#1f2937',
    text: {
      primary: '#f9fafb',
      secondary: '#9ca3af',
      disabled: '#6b7280',
    },
    border: '#374151',
    primary: '#60a5fa',
    secondary: '#9ca3af',
    success: '#34d399',
    warning: '#fbbf24',
    error: '#f87171',
  },
};

export type Theme = typeof lightTheme;
`;
}

/**
 * Generate CSS variables file
 */
export function generateCssVariables(task: TaskDocument): string {
  return `/**
 * CSS Variables
 *
 * ${task.description}
 *
 * @generated by Frontend Team
 */

:root {
  /* Color Palette */
  --color-primary-50: #eff6ff;
  --color-primary-100: #dbeafe;
  --color-primary-200: #bfdbfe;
  --color-primary-300: #93c5fd;
  --color-primary-400: #60a5fa;
  --color-primary-500: #3b82f6;
  --color-primary-600: #2563eb;
  --color-primary-700: #1d4ed8;
  --color-primary-800: #1e40af;
  --color-primary-900: #1e3a8a;

  /* Neutral Colors */
  --color-gray-50: #f9fafb;
  --color-gray-100: #f3f4f6;
  --color-gray-200: #e5e7eb;
  --color-gray-300: #d1d5db;
  --color-gray-400: #9ca3af;
  --color-gray-500: #6b7280;
  --color-gray-600: #4b5563;
  --color-gray-700: #374151;
  --color-gray-800: #1f2937;
  --color-gray-900: #111827;

  /* Semantic Colors */
  --color-success: #10b981;
  --color-warning: #f59e0b;
  --color-error: #ef4444;
  --color-info: #3b82f6;

  /* Shadows */
  --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);
  --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1);
  --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1);

  /* Transitions */
  --transition-fast: 150ms ease;
  --transition-normal: 250ms ease;
  --transition-slow: 350ms ease;
}
`;
}

/**
 * Generate component types file
 */
export function generateComponentTypes(
  task: TaskDocument,
  analysis: ComponentAnalysis
): string {
  const componentName = toComponentName(task.title);

  return `/**
 * Types for ${componentName}
 *
 * @generated by Frontend Team
 */

export interface ${componentName}Props {
  /** Optional CSS class name */
  className?: string;
  ${analysis.hasChildren ? '/** Child elements */\n  children?: React.ReactNode;' : ''}
  ${analysis.requiresAPI ? '/** Data to display */\n  data?: unknown;' : ''}
  /** Disabled state */
  disabled?: boolean;
  /** Click handler */
  onClick?: () => void;
}

export interface ${componentName}State {
  ${analysis.requiresState ? '/** Active state */\n  isActive: boolean;' : '// No state'}
  ${analysis.requiresAPI ? '/** Loading state */\n  isLoading: boolean;\n  /** Error state */\n  error?: Error;' : ''}
}

export type ${componentName}Variant = 'default' | 'primary' | 'secondary';

export type ${componentName}Size = 'small' | 'medium' | 'large';
`;
}
