/**
 * Vue Component Template
 *
 * Template for generating Vue components.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { ComponentAnalysis } from '../frontend-team.types';
import { toKebabCase } from '../utils';

/**
 * Generate Vue component code
 */
export function generateVueComponent(
  task: TaskDocument,
  componentName: string,
  analysis: ComponentAnalysis
): string {
  return `<template>
  <div class="${toKebabCase(componentName)}">
    <!-- ${task.description} -->
    ${analysis.hasChildren ? '<slot />' : `<span>${task.title}</span>`}
  </div>
</template>

<script setup lang="ts">
/**
 * ${componentName}
 *
 * ${task.description}
 *
 * @generated by Frontend Team
 */

${analysis.requiresState ? "import { ref } from 'vue';" : ''}

${analysis.requiresState ? "const isActive = ref(false);" : '// No state required'}
</script>

<style scoped>
.${toKebabCase(componentName)} {
  /* Component styles */
}
</style>
`;
}
