/**
 * Specialized Agents Module
 *
 * Provides concrete agent implementations built on the DI-based BaseAgent.
 *
 * @module core/agents/specialized
 */

export { CoderAgent, createCoderAgent, type CoderAgentConfig } from './coder-agent';
export {
  ArchitectAgent,
  createArchitectAgent,
  DocumentAnalysisPayloadSchema,
  ArchitectureDesignPayloadSchema,
  TechStackPayloadSchema,
  APIDesignPayloadSchema,
  ModuleBreakdownResponseSchema,
  ArchitectureResponseSchema,
  TechStackResponseSchema,
  APISpecResponseSchema,
  AnalysisDepth,
  ArchitectureStyle,
  type ArchitectAgentConfig,
  type DocumentAnalysisPayload,
  type ArchitectureDesignPayload,
  type TechStackPayload,
  type APIDesignPayload,
  type ModuleBreakdownResponse,
  type ArchitectureResponse,
  type TechStackResponse,
  type APISpecResponse,
} from './architect-agent';
export {
  ReviewerAgent,
  createReviewerAgent,
  ReviewPayloadSchema,
  CodeReviewResponseSchema,
  ReviewDecision,
  CommentSeverity,
  type ReviewerAgentConfig,
  type ReviewPayload,
  type CodeReviewResponse,
  type IGitHubClient,
  type ICIChecker,
  type PullRequestInfo,
} from './reviewer-agent';
export {
  TesterAgent,
  createTesterAgent,
  TestExecutionPayloadSchema,
  TestGenerationPayloadSchema,
  TestAnalysisPayloadSchema,
  GeneratedTestResponseSchema,
  TestAnalysisResponseSchema,
  CoverageStatus,
  IssueSeverity,
  type TesterAgentConfig,
  type TestExecutionPayload,
  type TestGenerationPayload,
  type TestAnalysisPayload,
  type GeneratedTestResponse,
  type TestAnalysisResponse,
  type ITestRunner,
  type TestRunResult,
  type FailedTest,
  type CoverageResult,
} from './tester-agent';
export {
  DocWriterAgent,
  createDocWriterAgent,
  DocumentationType,
  DocumentationFormat,
  DetailLevel,
  ChangeType,
  CodeDocumentationPayloadSchema,
  ReadmeGenerationPayloadSchema,
  ApiDocumentationPayloadSchema,
  ChangelogPayloadSchema,
  UserGuidePayloadSchema,
  CodeDocumentationResponseSchema,
  ReadmeResponseSchema,
  ApiDocumentationResponseSchema,
  ChangelogResponseSchema,
  UserGuideResponseSchema,
  type DocWriterAgentConfig,
  type CodeDocumentationPayload,
  type ReadmeGenerationPayload,
  type ApiDocumentationPayload,
  type ChangelogPayload,
  type UserGuidePayload,
  type CodeDocumentationResponse,
  type ReadmeResponse,
  type ApiDocumentationResponse,
  type ChangelogResponse,
  type UserGuideResponse,
} from './docwriter-agent';
export {
  ExplorerAgent,
  createExplorerAgent,
  SearchType,
  FileType,
  ExplorationDepth,
  SymbolType,
  DependencyType,
  FileStructureAnalysisPayloadSchema,
  CodeSearchPayloadSchema,
  DependencyAnalysisPayloadSchema,
  SymbolLookupPayloadSchema,
  CodebaseSummaryPayloadSchema,
  FileStructureResponseSchema,
  CodeSearchResponseSchema,
  DependencyAnalysisResponseSchema,
  SymbolLookupResponseSchema,
  CodebaseSummaryResponseSchema,
  type ExplorerAgentConfig,
  type FileStructureAnalysisPayload,
  type CodeSearchPayload,
  type DependencyAnalysisPayload,
  type SymbolLookupPayload,
  type CodebaseSummaryPayload,
  type FileStructureResponse,
  type CodeSearchResponse,
  type DependencyAnalysisResponse,
  type SymbolLookupResponse,
  type CodebaseSummaryResponse,
} from './explorer-agent';
export {
  LibrarianAgent,
  createLibrarianAgent,
  DocumentationSource,
  ReferenceType,
  SearchScope,
  ContentFormat,
  KnowledgeDomain,
  ApiDocLookupPayloadSchema,
  CodeExampleSearchPayloadSchema,
  BestPracticesLookupPayloadSchema,
  ReferenceSearchPayloadSchema,
  KnowledgeSynthesisPayloadSchema,
  ApiDocLookupResponseSchema,
  CodeExampleSearchResponseSchema,
  BestPracticesLookupResponseSchema,
  ReferenceSearchResponseSchema,
  KnowledgeSynthesisResponseSchema,
  type LibrarianAgentConfig,
  type ApiDocLookupPayload,
  type CodeExampleSearchPayload,
  type BestPracticesLookupPayload,
  type ReferenceSearchPayload,
  type KnowledgeSynthesisPayload,
  type ApiDocLookupResponse,
  type CodeExampleSearchResponse,
  type BestPracticesLookupResponse,
  type ReferenceSearchResponse,
  type KnowledgeSynthesisResponse,
} from './librarian-agent';
