/**
 * API Tests Template
 *
 * Generates API test files using supertest.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { APIAnalysis } from '../backend-team.types';
import { toResourceName, toPascalCase } from '../utils/naming.utils';

/**
 * Generate API tests
 */
export function generateAPITests(
  task: TaskDocument,
  analysis: APIAnalysis
): GeneratedFile {
  const resourceName = toResourceName(task.title);
  const typeName = toPascalCase(resourceName);

  const content = `/**
 * API Tests for ${task.title}
 *
 * @generated by Backend Team
 */

import request from 'supertest';
import { app } from '../src/app';

describe('${typeName} API', () => {
  ${analysis.httpMethods.includes('GET') ? `
  describe('GET /${resourceName}s', () => {
    it('should return a list of ${resourceName}s', async () => {
      const response = await request(app)
        .get('/${resourceName}s')
        ${analysis.requiresAuth ? `.set('Authorization', 'Bearer test-token')` : ''};

      expect(response.status).toBe(200);
      expect(response.body).toHaveProperty('data');
      expect(Array.isArray(response.body.data)).toBe(true);
    });

    it('should support pagination', async () => {
      const response = await request(app)
        .get('/${resourceName}s?page=1&limit=10')
        ${analysis.requiresAuth ? `.set('Authorization', 'Bearer test-token')` : ''};

      expect(response.status).toBe(200);
      expect(response.body).toHaveProperty('page', 1);
      expect(response.body).toHaveProperty('limit', 10);
    });
  });

  describe('GET /${resourceName}s/:id', () => {
    it('should return a ${resourceName} by ID', async () => {
      const response = await request(app)
        .get('/${resourceName}s/test-id')
        ${analysis.requiresAuth ? `.set('Authorization', 'Bearer test-token')` : ''};

      expect([200, 404]).toContain(response.status);
    });

    it('should return 404 for non-existent ${resourceName}', async () => {
      const response = await request(app)
        .get('/${resourceName}s/non-existent-id')
        ${analysis.requiresAuth ? `.set('Authorization', 'Bearer test-token')` : ''};

      expect(response.status).toBe(404);
    });
  });` : ''}

  ${analysis.httpMethods.includes('POST') ? `
  describe('POST /${resourceName}s', () => {
    it('should create a new ${resourceName}', async () => {
      const response = await request(app)
        .post('/${resourceName}s')
        ${analysis.requiresAuth ? `.set('Authorization', 'Bearer test-token')` : ''}
        .send({ name: 'Test ${typeName}' });

      expect([201, 400]).toContain(response.status);
    });

    it('should validate required fields', async () => {
      const response = await request(app)
        .post('/${resourceName}s')
        ${analysis.requiresAuth ? `.set('Authorization', 'Bearer test-token')` : ''}
        .send({});

      expect(response.status).toBe(400);
    });
  });` : ''}

  ${analysis.httpMethods.includes('PUT') ? `
  describe('PUT /${resourceName}s/:id', () => {
    it('should update a ${resourceName}', async () => {
      const response = await request(app)
        .put('/${resourceName}s/test-id')
        ${analysis.requiresAuth ? `.set('Authorization', 'Bearer test-token')` : ''}
        .send({ name: 'Updated ${typeName}' });

      expect([200, 404]).toContain(response.status);
    });
  });` : ''}

  ${analysis.httpMethods.includes('DELETE') ? `
  describe('DELETE /${resourceName}s/:id', () => {
    it('should delete a ${resourceName}', async () => {
      const response = await request(app)
        .delete('/${resourceName}s/test-id')
        ${analysis.requiresAuth ? `.set('Authorization', 'Bearer test-token')` : ''};

      expect([204, 404]).toContain(response.status);
    });
  });` : ''}

  ${analysis.requiresAuth ? `
  describe('Authentication', () => {
    it('should return 401 without auth token', async () => {
      const response = await request(app).get('/${resourceName}s');
      expect(response.status).toBe(401);
    });
  });` : ''}
});
`;

  return {
    path: `tests/api/${resourceName}.api.test.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: true,
  };
}
