/**
 * Integration Tests Template
 *
 * Generates integration test files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { APIAnalysis } from '../backend-team.types';
import { toResourceName, toPascalCase } from '../utils/naming.utils';

/**
 * Generate integration tests
 */
export function generateIntegrationTests(
  task: TaskDocument,
  analysis: APIAnalysis
): GeneratedFile {
  const resourceName = toResourceName(task.title);
  const typeName = toPascalCase(resourceName);

  const content = `/**
 * Integration Tests for ${task.title}
 *
 * @generated by Backend Team
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

describe('${typeName} Integration', () => {
  beforeAll(async () => {
    // Setup test database
  });

  afterAll(async () => {
    await prisma.$disconnect();
  });

  beforeEach(async () => {
    // Clean up before each test
  });

  describe('CRUD Operations', () => {
    it('should create and retrieve a ${resourceName}', async () => {
      // Create
      const created = await prisma.${resourceName}.create({
        data: { name: 'Test' },
      });

      expect(created).toHaveProperty('id');

      // Retrieve
      const found = await prisma.${resourceName}.findUnique({
        where: { id: created.id },
      });

      expect(found).toEqual(created);
    });

    it('should update a ${resourceName}', async () => {
      const created = await prisma.${resourceName}.create({
        data: { name: 'Original' },
      });

      const updated = await prisma.${resourceName}.update({
        where: { id: created.id },
        data: { name: 'Updated' },
      });

      expect(updated.name).toBe('Updated');
    });

    it('should delete a ${resourceName}', async () => {
      const created = await prisma.${resourceName}.create({
        data: { name: 'To Delete' },
      });

      await prisma.${resourceName}.delete({
        where: { id: created.id },
      });

      const found = await prisma.${resourceName}.findUnique({
        where: { id: created.id },
      });

      expect(found).toBeNull();
    });
  });

  ${analysis.requiresDatabase ? `
  describe('Database Constraints', () => {
    it('should enforce unique constraints', async () => {
      // Test unique constraints
    });

    it('should handle foreign key relationships', async () => {
      // Test relationships
    });
  });` : ''}
});
`;

  return {
    path: `tests/integration/${resourceName}.integration.test.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: true,
  };
}
