/**
 * Middleware Tests Template
 *
 * Generates middleware test files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { toCamelCase, toKebabCase } from '../utils/naming.utils';

/**
 * Generate middleware tests
 */
export function generateMiddlewareTests(task: TaskDocument): GeneratedFile {
  const middlewareName = toCamelCase(task.title.replace(/middleware/gi, ''));

  const content = `/**
 * Middleware Tests for ${task.title}
 *
 * @generated by Backend Team
 */

import { Request, Response, NextFunction } from 'express';
import { ${middlewareName} } from '../src/middleware/${toKebabCase(task.title)}.middleware';

describe('${task.title} Middleware', () => {
  let mockReq: Partial<Request>;
  let mockRes: Partial<Response>;
  let nextFn: NextFunction;

  beforeEach(() => {
    mockReq = {};
    mockRes = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn().mockReturnThis(),
    };
    nextFn = jest.fn();
  });

  it('should call next() on success', () => {
    const middleware = ${middlewareName}();
    middleware(mockReq as Request, mockRes as Response, nextFn);
    expect(nextFn).toHaveBeenCalled();
  });

  it('should handle errors', () => {
    const middleware = ${middlewareName}();
    // Test error handling
  });
});
`;

  return {
    path: `tests/middleware/${toKebabCase(task.title)}.middleware.test.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: true,
  };
}
