/**
 * Model Tests Template
 *
 * Generates model test files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { ModelAnalysis } from '../backend-team.types';

/**
 * Generate model tests
 */
export function generateModelTests(
  _task: TaskDocument,
  analysis: ModelAnalysis
): GeneratedFile {
  const content = `/**
 * Model Tests for ${analysis.entityName}
 *
 * @generated by Backend Team
 */

import { ${analysis.entityName} } from '@prisma/client';
import { ${analysis.entityName.toLowerCase()}Repository } from '../src/repositories/${analysis.entityName.toLowerCase()}.repository';

describe('${analysis.entityName} Model', () => {
  describe('Fields', () => {
    ${analysis.fields.map((field) => `
    it('should have ${field.name} field', () => {
      const model = {} as ${analysis.entityName};
      expect('${field.name}' in model || true).toBe(true);
    });`).join('\n')}
  });

  describe('Repository', () => {
    it('should find all', async () => {
      const results = await ${analysis.entityName.toLowerCase()}Repository.findAll();
      expect(Array.isArray(results)).toBe(true);
    });

    it('should find by id', async () => {
      const result = await ${analysis.entityName.toLowerCase()}Repository.findById('test-id');
      // Result may be null
    });
  });

  ${analysis.relations.length > 0 ? `
  describe('Relations', () => {
    ${analysis.relations.map((relation) => `
    it('should have ${relation.type} relation with ${relation.target}', () => {
      // Test relation
    });`).join('\n')}
  });` : ''}
});
`;

  return {
    path: `tests/models/${analysis.entityName.toLowerCase()}.model.test.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: true,
  };
}
