/**
 * Service Tests Template
 *
 * Generates service test files.
 *
 * Feature: Team System
 */

import { TaskDocument } from '../../../team-types';
import { GeneratedFile } from '../../development-team';
import { toServiceName, toResourceName } from '../utils/naming.utils';

/**
 * Generate service tests
 */
export function generateServiceTests(task: TaskDocument): GeneratedFile {
  const serviceName = toServiceName(task.title);
  const resourceName = toResourceName(task.title);

  const content = `/**
 * Service Tests for ${serviceName}
 *
 * @generated by Backend Team
 */

import { ${serviceName} } from '../src/services/${resourceName}.service';

describe('${serviceName}', () => {
  let service: ${serviceName};

  beforeEach(() => {
    service = new ${serviceName}();
  });

  describe('findAll', () => {
    it('should return paginated results', async () => {
      const result = await service.findAll({ page: 1, limit: 10 });
      expect(result).toHaveProperty('data');
      expect(result).toHaveProperty('total');
      expect(result).toHaveProperty('page', 1);
      expect(result).toHaveProperty('limit', 10);
    });
  });

  describe('findById', () => {
    it('should throw error for non-existent id', async () => {
      await expect(service.findById('non-existent')).rejects.toThrow();
    });
  });

  describe('create', () => {
    it('should create a new record', async () => {
      // Test creation
    });
  });

  describe('update', () => {
    it('should update an existing record', async () => {
      // Test update
    });
  });

  describe('delete', () => {
    it('should delete an existing record', async () => {
      // Test deletion
    });
  });
});
`;

  return {
    path: `tests/services/${resourceName}.service.test.ts`,
    content,
    language: 'typescript',
    linesOfCode: content.split('\n').length,
    isTest: true,
  };
}
